### ISSUE TITLE
generate ts types with type keyword instead of interface

### ISSUE THREAD

**Issue by oscartbeaumont** [specta-rs/specta#19]
oscartbeaumont/rspc#83

**Comment by coopbri** [comment]
I read the discussion there, is there still a way in specta to export a TypeScript `interface` instead of a `type`? Since `interface` and `type` are both TS language features (I really wish they didn't do this and just had one way to do it, but here we are), I think it makes sense to support both

**Comment by oscartbeaumont** [comment]
Can you explain more about your usecase? Is it just preference or are there technical merits?

**Comment by coopbri** [comment]
Good q, I suppose a bit of both but honestly on the side of preference. https://github.com/microsoft/Typescript/wiki/Performance#preferring-interfaces-over-intersections explains some details about where interfaces are ideal, for me it is the cleanliness of extending (hence leaning on preference!).

I believe having the ability to optionally choose between `type` and `interface` (defaulting to `type` for simplicity and reducing user friction, as you already decided years ago) would be a great addition! Supporting as much of TypeScript as possible makes `specta` even more versatile. The `Type` proc macro could be extended to handle this, perhaps by inspecting a custom attribute like `#[ts_interface]`, or any other suggestions you have if this is interesting to you. Without this option, an important TypeScript feature (the distinction between type and interface) remains unsupported, which feels like a missed opportunity and ignoring a key part of TypeScript's type system/syntax.

If this is something you're interested in, I would be happy to contribute a PR!
