### ISSUE TITLE
`specta(skip)` for enum fields

### ISSUE THREAD

**Issue by Brendonovich** [specta-rs/specta#25]

**Comment by IgnisDa** [comment]
Hey @Brendonovich @oscartbeaumont! The Discord invite on the rspc docs is outdated. Could you please drop the invite link here? I have a problem related to this issue.

**Comment by Brendonovich** [comment]
I've updated the invite link in the readme

**Comment by oscartbeaumont** [comment]
If I had to guess the issue your hitting would be #153 but definitely love to hear your problem!
