### ISSUE TITLE
Using external types

### ISSUE THREAD

**Issue by cAttte** [specta-rs/specta#284]
hi! is there a reasonable way to use specta on types from external crates, given that obviously you can't apply `derive(Type)` on an already-defined, let alone external, type? one workaround is manually converting them to internal wrapper types, but that's a hassle

**Comment by Brendonovich** [comment]
The recommended approach is to define your own types that mirror the shape of the third party types, and use them in `#[specta(type = ...)]` field attributes. You can't implement Type directly for a crate you don't own.

**Comment by cAttte** [comment]
oops sorry, completely forgot about the orphan rule for that 2nd comment lol. the attribute you mentioned sounds like what i'm looking for (reminds me of serde's remote), but i don't really know what you mean. the `specta` attribute doesn't seem to take any arguments? thanks!

**Comment by amosjyng** [comment]
Looks like [this issue](https://github.com/specta-rs/specta/issues/210#issuecomment-1874727304) has an example implementation. It turns out this compiles fine:

```rs
#[derive(Debug, Clone, specta::Type)]
pub struct WrongDef {
    pub wrong: String,
}

#[derive(specta::Type)]
pub struct AsciiCastData {
    #[specta(type = WrongDef)]
    pub header: Header,
    #[specta(type = WrongDef)]
    pub entries: Vec<Entry>,
}
```

Unfortunately this does sort of remove one of the benefits of type-checking, if I have to personally remember to make downstream changes to an updated type.

**Comment by cAttte** [comment]
funny how we made the same issue a few days apart! thanks for the link, i agree the solution (like serde's) is pretty ugly but i guess that's just a consequence of rust's complete lack of reflection :'(. as a random note, i've been looking into [`serde_reflection`](https://docs.rs/serde-reflection) and [`serde_generate`](https://docs.rs/serde-generate/latest/serde_generate/) for generating format descriptions from just the serde impls, but i'm not sure how much potential it has. anyway, closing this now
