### ISSUE TITLE
Upgrading from 2.0.0-rc.9 to -rc.20, how to obtain ts_with_cfg() outcome?

### ISSUE THREAD

**Issue by johncarmack1984** [specta-rs/specta#291]
Hello! Huge fan of specta, it's a godsend for team projects that move quickly!

I'm currently updating a project from v2.0.0-rc.9 to -rc.20. We were previously relying entirely on `specta::export::ts_with_cfg()` to export our types, but while upgrading, I noticed `ts_with_cfg` was first [moved to `specta_util`](https://github.com/specta-rs/specta/commit/24978230d01be0daec984bced3fe2a64ebd92fba#diff-b1f8cddb5ed9e61ad69a68f4c22bcc54431470c827bed4b8b72665a3645a4d8bL1) then later [removed entirely](https://github.com/specta-rs/specta/commit/35846dfe043b4a9b192cd533d715bb27b3fbb431).

I did a bit of digging, but kept coming up empty while looking for a 1:1 substitute within the codebase, so thought I would ask: what syntax would a specta user call in rc.20 to create the same outcome that rc.9 would create with `specta::export::ts_with_cfg()`?

Thanks so much and sorry if this is a bother!

**Comment by oscartbeaumont** [comment]
Changes:
 - `specta::export` is now language agnostic and is at `specta_util::export` (requires `export` feature on `specta_util` crate)
 - It returns a `TypeCollection` which has an `export` and `export_to` method. This type allows us to generalise the export logic and let the end-user use it however they want Eg. you can create your own `TypeCollection` and/or add extra types to it.
 - `specta::ts::ExportConfig` is now `specta_typescript::Typescript`.

With all this `specta::export::ts_with_cfg()` is now effectively:
```rs
specta_util::export()
        .export_to(specta_typescript::Typescript::default(), "./bindings.ts")
        .unwrap();
```

I have updated the [example](https://github.com/specta-rs/specta/blob/main/examples/examples/export.rs) to showcase the API a bit better. Let me know if you run into any other problems or have more questions!

**Comment by johncarmack1984** [comment]
Thank you!!
