### ISSUE TITLE
2.x.x: `chrono` types shouldn't be just strings

### ISSUE THREAD

**Issue by cognivore** [specta-rs/specta#293]
# Why?

When I enabled `chrono` feature flag, I expected something more fine-grained than `string` as the output type.
At least some type which denotes the original intent of time-related code, perhaps something wrapped in newtype even!

Observed outcome was that every chrono type I can fathom translates into `string`. 

# What? 

 - Have a discussion about the most reasonable and portable type representation for time-related types
 - Have it implemented
 - Have "stringly-typed" chrono available as an escape-hatch.

**Comment by cognivore** [comment]
Oh how cringe! I'll open this in serde then I guess? :D 

It's really crazy that we have all these great facilities for distinguishing different types of date semantics and we lose them all hoping that the users will parse out the semantics based on the contents of ISO string.

FWIW, I have made the following hack:

```
#[derive(Debug, Clone, Copy, Serialize, Deserialize, specta::Type)]
pub struct WrappedNaiveDate {
    pub naive_date: NaiveDate,
}

impl From<DateTime<Utc>> for WrappedUtcDateTime {
    fn from(dt: DateTime<Utc>) -> Self {
        Self { utc_date_time: dt }
    }
}

impl From<WrappedUtcDateTime> for DateTime<Utc> {
    fn from(wrapped: WrappedUtcDateTime) -> Self {
        wrapped.utc_date_time
    }
}
```

```
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct Task {
    pub name: String,
    pub technology: Technology,
    pub task_type: TaskType,
    pub description: String,
    #[specta(type = crate::wrapped_chrono::WrappedUtcDateTime)]
    pub last_updated: DateTime<Utc>,
}
```

I hope that it will be enough to transparently interoperate hither and thither, if it won't be, I'll report in this issue.

Thank you for your feedback, this issue is indeed misplaced, so I'll close it, but I'll post my findings here so that people looking up for the reasons for this design will be able to find it and read about things they can do about it.

**Comment by oscartbeaumont** [comment]
>  I'll open this in serde then I guess?

It probally won't get anywhere sadly because Serde copies the JSON spec. If the JSON spec had Date's I think this whole thing would be much nicer but atlas it does not.
